baseURL: "https://ahmedelfatmaoui.github.io/" 
title: Ahmed El Fatmaoui
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: aelfatmaoui

taxonomies:
    tag: tags

menu:
    main:
          - name: Courses
            url: /courses/
            weight: 2
          - name: Papers
            url: /papers/
        #   # weight: 1
        # - name: Design
        #   url: /design/
        #   weight: 3
        # - name: Tags
        #   url: /tags/
        #   weight: 5     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "Welcome! I am a fourth-year  PhD Candidate in Economics at the University of Oklahoma, Norman. I specialize in labor economics, the economics of education, and health economics. Before coming to Norman, I received a Master's in Applied Mathematics from the University of Central Oklahoma. My current research centers on college costs, amenities, and relevant policies that shape student outcomes. In previous work, I delved into the study of policies impacting vaccine development."
    author: Ahmed El Fatmaoui
    #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ahmed El Fatmaoui
          subtitle: "Welcome! I am a fourth-year PhD Candidate in Economics at The University of Oklahoma, Norman. I specialize in labor economics, the economics of education, and health economics. Before coming to Norman, I received a Master's in Applied Mathematics from the University of Central Oklahoma. My current research centers on college costs, amenities, and relevant policies that shape student outcomes. In previous work, I delved into the study of policies impacting vaccine development."
          imageUrl: "/picture.jpeg"
          imageWidth: 270
          imageHeight: 270
          imageTitle: Ahmed El Fatmaoui
          buttons:
              - name: Courses
                url: /courses/
              - name: Papers
                url: /papers/
            # - name: Design
            #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:aelfatmaoui@ou.edu
        - name: Location
          url: /location/
        # - name: Office Hours
        #   url: /officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: GitHub
        #   url: https://github.com/pmichaillat?tab=repositories
        # - name: Substack
        #   url: https://pmichaillat.substack.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Ahmed El Fatmaoui"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
