baseURL: "https://ahmedelfatmaoui.github.io/" 
#baseURL: "https://github.com/ahmedelfatmaoui/ahmedelfatmaoui.github.io" 

title: Ahmed El Fatmaoui
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: aelfatmaoui

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers (coming soon!)
          # url: /papers/
          # weight: 1
        - name: Courses (coming soon!)
          # url: /courses/
          # weight: 2
        # - name: Design
        #   url: /design/
        #   weight: 3
        # - name: Tags
        #   url: /tags/
        #   weight: 5     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a Ph.D. student in the Department of Economics at The University of Oklahoma, Norman"
    author: Ahmed El Fatmaoui
    #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ahmed El Fatmaoui
          subtitle: "I am a Ph.D. student in the Department of Economics at The University of Oklahoma, Norman"
          imageUrl: "/picture.jpeg"
          imageWidth: 270
          imageHeight: 270
          imageTitle: Ahmed El Fatmaoui
          # buttons:
          #   - name: Papers (coming soon!)
          #     url: /papers/
          #   - name: Courses (coming soon!)
          #     url: /courses/ 
            # - name: Design
            #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:aelfatmaoui@ou.edu
        - name: Location
          url: /location/
        # - name: Office Hours
        #   url: /officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: GitHub
        #   url: https://github.com/pmichaillat?tab=repositories
        # - name: Substack
        #   url: https://pmichaillat.substack.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Ahmed El Fatmaoui"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
