baseURL: "https://ahmedelfatmaoui.github.io/" 
title: Ahmed El Fatmaoui
paginate: 14
theme: PaperMod

enableInlineShortcodes: true 
enableRobotsTXT: false  ### show pic true

social:
    twitter: aelfatmaoui

taxonomies:
    tag: tags

menu:
    main:
          - name: Teaching
            url: /courses/
            weight: 1
          - name: Research
            url: /papers/
            weight: 2
          - name: CV
            url: /cv.pdf
            weight: 3
        #   # weight: 1
        # - name: Design
        #   url: /design/
        #   weight: 3
        # - name: Tags
        #   url: /tags/
        #   weight: 5     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: |
        Welcome!
        
        I am a Ph.D. Economics candidate at the University of Oklahoma, Norman. I specialize in labor economics, the economics of education, and health economics. Before coming to Norman, I received a Master's in Applied Mathematics from the University of Central Oklahoma. 
        
        My current research centers on college costs, amenities, and the policies that shape student outcomes. Additionally, I examine the effects of policy on vaccine development and assess the impact of vaccination on the health outcomes of pregnant women and infants. My research has earned recognition through the Southern Economic Association Graduate Student Award, the OU Dodge Family College of Arts and Sciences Dissertation Research Fellowship, and the Chong Liew Summer Research Award.
        
        As a graduate instructor at the University of Oklahoma, I have independently taught introductory microeconomics, introductory macroeconomics, and business statistics. Additionally, while pursuing my master's in Applied Mathematics at the University of Central Oklahoma, I taught Intermediate Algebra.
    author: Ahmed El Fatmaoui
    googleAnalyticsID: "G-WHEYZ77X40"
    DateFormat: "January 2024"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true 
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true  
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true 
    ShowWordCount: false
    UseHugoToc: true 
    comments: false
    math: true
    profileMode:
          enabled: true 
          title: Ahmed El Fatmaoui
          subtitle: |
                <div style="margin-bottom: 0.2cm;"></div>
                Welcome! 
                <div style="margin-bottom: 0.5cm;"></div>
                I am a Ph.D. Economics candidate at The University of Oklahoma, Norman. I specialize in labor economics, the economics of education, and health economics. Before coming to Norman, I received a Master's in Applied Mathematics from the University of Central Oklahoma. 
                <div style="margin-bottom: 0.5cm;"></div>
                My current research centers on college costs, amenities, and the policies that shape student outcomes. Additionally, I examine the effects of policy on vaccine development and assess the impact of vaccination on the health outcomes of pregnant women and infants. My research has been recognized with the Southern Economic Association Graduate Student Award, the OU Dodge Family College of Arts and Sciences Dissertation Research Fellowship, and the Chong Liew Summer Research Award.
                <div style="margin-bottom: 0.5cm;"></div>
                As a graduate instructor at the University of Oklahoma, I have independently taught introductory microeconomics, introductory macroeconomics, and business statistics. Additionally, while pursuing my master's in Applied Mathematics at the University of Central Oklahoma, I taught Intermediate Algebra.
                <div style="margin-bottom: 0.5cm;"></div>
          imageUrl: "/picture.jpeg"
          imageWidth: 280
          imageHeight: 300
          imageTitle: Ahmed El Fatmaoui
          buttons:
              - name: Teaching
                url: /courses/
                weight: 1
              - name: Research
                url: /papers/
                weight: 2
              - name: CV
                url: /cv.pdf
                weight: 3
              # - name: Design
              #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:aelfatmaoui@ou.edu
        - name: Location
          url: /location/
        # - name: Office Hours
        #   url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=EdHxr3EAAAAJ&hl=en
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/ahmedelfatmaoui?tab=repositories
        # - name: Substack
        #   url: https://pmichaillat.substack.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ahmed El Fatmaoui"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: true
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
